services:
  postgres:
    image: postgres:15
    container_name: kaeruashi-postgres
    environment:
      POSTGRES_USER: kaeruashi
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kaeruashi-dev
      TZ: 'UTC'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaeruashi"]
      interval: 3s
      timeout: 2s
      retries: 5
