services:
  postgres:
    image: postgres:15
    container_name: pond-postgres
    environment:
      POSTGRES_USER: pond
      POSTGRES_PASSWORD: pondpass
      POSTGRES_DB: pond_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pond"]
      interval: 3s
      timeout: 2s
      retries: 5
