// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/kaerubo/kaeruashi/internal/handler"
	"github.com/kaerubo/kaeruashi/internal/infra/postgres"
	"github.com/kaerubo/kaeruashi/internal/usecase"
)

// Injectors from wire.go:

func InitializeHandler(db *sql.DB) *handler.KeroHandler {
	keroRepository := postgres.NewKeroRepository(db)
	keroCreator := usecase.NewKeroCreator(keroRepository)
	keroByIDReader := usecase.NewKeroByIDReader(keroRepository)
	keroLister := usecase.NewKeroLister(keroRepository)
	keroUpdater := usecase.NewKeroUpdater(keroRepository)
	keroDeleter := usecase.NewKeroDeleter(keroRepository)
	keroHandler := handler.NewKeroHandler(keroCreator, keroByIDReader, keroLister, keroUpdater, keroDeleter)
	return keroHandler
}
