// Code generated by MockGen. DO NOT EDIT.
// Source: kero_repository.go
//
// Generated by this command:
//
//	mockgen -source=kero_repository.go -destination=mock/kero_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/kaerubo/kaeruashi/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockKeroInserter is a mock of KeroInserter interface.
type MockKeroInserter struct {
	ctrl     *gomock.Controller
	recorder *MockKeroInserterMockRecorder
	isgomock struct{}
}

// MockKeroInserterMockRecorder is the mock recorder for MockKeroInserter.
type MockKeroInserterMockRecorder struct {
	mock *MockKeroInserter
}

// NewMockKeroInserter creates a new mock instance.
func NewMockKeroInserter(ctrl *gomock.Controller) *MockKeroInserter {
	mock := &MockKeroInserter{ctrl: ctrl}
	mock.recorder = &MockKeroInserterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeroInserter) EXPECT() *MockKeroInserterMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockKeroInserter) Insert(ctx context.Context, k *entity.Kero) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockKeroInserterMockRecorder) Insert(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockKeroInserter)(nil).Insert), ctx, k)
}

// MockKeroByIDFinder is a mock of KeroByIDFinder interface.
type MockKeroByIDFinder struct {
	ctrl     *gomock.Controller
	recorder *MockKeroByIDFinderMockRecorder
	isgomock struct{}
}

// MockKeroByIDFinderMockRecorder is the mock recorder for MockKeroByIDFinder.
type MockKeroByIDFinderMockRecorder struct {
	mock *MockKeroByIDFinder
}

// NewMockKeroByIDFinder creates a new mock instance.
func NewMockKeroByIDFinder(ctrl *gomock.Controller) *MockKeroByIDFinder {
	mock := &MockKeroByIDFinder{ctrl: ctrl}
	mock.recorder = &MockKeroByIDFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeroByIDFinder) EXPECT() *MockKeroByIDFinderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockKeroByIDFinder) FindByID(ctx context.Context, id string) (*entity.Kero, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Kero)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockKeroByIDFinderMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockKeroByIDFinder)(nil).FindByID), ctx, id)
}

// MockKeroFinder is a mock of KeroFinder interface.
type MockKeroFinder struct {
	ctrl     *gomock.Controller
	recorder *MockKeroFinderMockRecorder
	isgomock struct{}
}

// MockKeroFinderMockRecorder is the mock recorder for MockKeroFinder.
type MockKeroFinderMockRecorder struct {
	mock *MockKeroFinder
}

// NewMockKeroFinder creates a new mock instance.
func NewMockKeroFinder(ctrl *gomock.Controller) *MockKeroFinder {
	mock := &MockKeroFinder{ctrl: ctrl}
	mock.recorder = &MockKeroFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeroFinder) EXPECT() *MockKeroFinderMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockKeroFinder) FindAll(ctx context.Context) ([]*entity.Kero, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.Kero)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockKeroFinderMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockKeroFinder)(nil).FindAll), ctx)
}

// MockKeroUpdater is a mock of KeroUpdater interface.
type MockKeroUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockKeroUpdaterMockRecorder
	isgomock struct{}
}

// MockKeroUpdaterMockRecorder is the mock recorder for MockKeroUpdater.
type MockKeroUpdaterMockRecorder struct {
	mock *MockKeroUpdater
}

// NewMockKeroUpdater creates a new mock instance.
func NewMockKeroUpdater(ctrl *gomock.Controller) *MockKeroUpdater {
	mock := &MockKeroUpdater{ctrl: ctrl}
	mock.recorder = &MockKeroUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeroUpdater) EXPECT() *MockKeroUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockKeroUpdater) Update(ctx context.Context, k *entity.Kero) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockKeroUpdaterMockRecorder) Update(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockKeroUpdater)(nil).Update), ctx, k)
}

// MockKeroDeleter is a mock of KeroDeleter interface.
type MockKeroDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockKeroDeleterMockRecorder
	isgomock struct{}
}

// MockKeroDeleterMockRecorder is the mock recorder for MockKeroDeleter.
type MockKeroDeleterMockRecorder struct {
	mock *MockKeroDeleter
}

// NewMockKeroDeleter creates a new mock instance.
func NewMockKeroDeleter(ctrl *gomock.Controller) *MockKeroDeleter {
	mock := &MockKeroDeleter{ctrl: ctrl}
	mock.recorder = &MockKeroDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeroDeleter) EXPECT() *MockKeroDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockKeroDeleter) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKeroDeleterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKeroDeleter)(nil).Delete), ctx, id)
}
